#!/bin/sh

function log() {
	local color=$1
	local msg=$2
	echo -e "\033[1;${color}m$msg\033[m"
}

function confirm() {
	local msg="$1"
	read -p "$msg ? (y/n) [n] " ok
	if [ "$ok" == "y" ]; then
		return 1
	fi
	return 0
}

DL_REPO_ROOT="https://github.com/CheyiLin/linux-res/raw/master"

# create titan group
groupadd -f -g 971 titan

echo
log 32 "Install Pre-Requirements ..."

# install pre-requirements
yum install -q -y vim screen lrzsz openssh-clients wget yum-plugin-security yum-utils sudo bind-utils man

# install repo rpms
rpm -ivU $DL_REPO_ROOT/centos6/yum-repos/epel-release-6-8.noarch.rpm
rpm -ivU $DL_REPO_ROOT/centos6/yum-repos/remi-release-6.rpm
rpm -ivU $DL_REPO_ROOT/centos6/yum-repos/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm

yum update -q -y epel-release remi-release rpmforge-release
yum-config-manager -q --enable remi remi-php56 > /dev/null

wget -q -O /etc/yum.repos.d/10gen.repo $DL_REPO_ROOT/centos6/yum-repos/10gen.repo
wget -q -O /etc/yum.repos.d/nginx.repo $DL_REPO_ROOT/centos6/yum-repos/nginx.repo
wget -q -O /etc/yum.repos.d/rsyslogall.repo $DL_REPO_ROOT/centos6/yum-repos/rsyslogall.repo
wget -q -O /etc/yum.repos.d/WANdisco.repo $DL_REPO_ROOT/centos6/yum-repos/WANdisco.repo
wget -q -O /tmp/RPM-GPG-KEY-WANdisco http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco && \
	rpm --import /tmp/RPM-GPG-KEY-WANdisco && rm -f /tmp/RPM-GPG-KEY-WANdisco

echo
log 32 "Install Runtime Requirements ..."

# install runtime requirements
yum update -q -y rsyslog mysql mysql-libs
yum install -q -y rsyslog-mysql mysql mysql-libs mysql-devel
yum install -q -y htop lsof strace multitail sysstat rsync numactl
yum install -q -y gcc gcc-c++ libtool make patch subversion git
yum install -q -y zlib zlib-devel bzip2 bzip2-devel readline readline-devel libuuid libuuid-devel
yum install -q -y gdbm gdbm-devel sqlite sqlite-devel openssl openssl-devel

rpm -ivU $DL_REPO_ROOT/centos6/dist/binaries/mongodb-org-shell-2.6.12-1.x86_64.rpm

echo
log 32 "Apply System Configurations ..."

# apply system configs
cp /etc/screenrc /etc/screenrc.bak
wget -q -O /etc/screenrc $DL_REPO_ROOT/centos6/etc/screenrc
cp /etc/sysctl.conf /etc/sysctl.conf.bak
wget -q -O /etc/sysctl.conf $DL_REPO_ROOT/centos6/etc/sysctl.conf
wget -q -O /etc/rsyslog.d/titanlog.conf $DL_REPO_ROOT/centos6/etc/rsyslog.d/titanlog.conf
wget -q -O /etc/security/limits.d/titan.conf $DL_REPO_ROOT/centos6/etc/security/limits.d/titan.conf

# disable services
chkconfig postfix off

echo
# (optional) install cmake
confirm "* Install CMake"
if [ "$?" == 1 ]; then
	wget -O /tmp/cmake-Linux-x86_64.sh \
		$DL_REPO_ROOT/centos6/dist/binaries/cmake-3.5.2-Linux-x86_64.sh && \
		sh /tmp/cmake-Linux-x86_64.sh --skip-license --exclude-subdir --prefix=/usr/local
fi

echo
# (optional) install nginx + php-fpm
confirm "* Install Nginx Web Server + PHP-FPM"
if [ "$?" == 1 ]; then
	yum install -q -y nginx php php-fpm php-opcache php-pecl-apcu
	yum install -q -y php-mysqlnd php-pecl-mongo phpMyAdmin
	chkconfig nginx on
	chkconfig php-fpm on
	
	mkdir -p /etc/nginx/ssl /etc/nginx/conf.d/apps
	wget -q -O /etc/nginx/ssl/dhparam.pem $DL_REPO_ROOT/centos6/etc/nginx/ssl/dhparam.pem
	cp /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
	wget -q -O /etc/nginx/conf.d/default.conf $DL_REPO_ROOT/centos6/etc/nginx/conf.d/default.conf
	wget -q -O /etc/nginx/conf.d/apps/phpmyadmin.conf.off $DL_REPO_ROOT/centos6/etc/nginx/conf.d/apps/phpmyadmin.conf
	
	/etc/init.d/php-fpm start
	/etc/init.d/nginx start
fi

echo
# (optional) install redis server
confirm "* Install Redis Server"
if [ "$?" == 1 ]; then
	yum install -q -y redis
	chkconfig redis on
	
	cp /etc/redis.conf /etc/redis.conf.bak
	wget -q -O /etc/redis.conf $DL_REPO_ROOT/centos6/etc/redis.conf
	
	/etc/init.d/redis start
fi

echo
# (optional) install mysql server
confirm "* Install MySQL Server"
if [ "$?" == 1 ]; then
	yum install -q -y mysql-server
	chkconfig mysqld on
	
	cp /etc/my.cnf /etc/my.cnf.bak
	wget -q -O /etc/my.cnf $DL_REPO_ROOT/centos6/etc/my.cnf
	
	/etc/init.d/mysqld start
fi

echo
# (optional) install mongodb server
confirm "* Install MongoDB Server"
if [ "$?" == 1 ]; then
	yum install -q -y sysstat numactl
	rpm -ivU $DL_REPO_ROOT/centos6/dist/binaries/mongodb-org-tools-2.6.12-1.x86_64.rpm
	rpm -ivU $DL_REPO_ROOT/centos6/dist/binaries/mongodb-org-mongos-2.6.12-1.x86_64.rpm
	rpm -ivU $DL_REPO_ROOT/centos6/dist/binaries/mongodb-org-server-2.6.12-1.x86_64.rpm
	rpm -ivU $DL_REPO_ROOT/centos6/dist/binaries/mongodb-org-2.6.12-1.x86_64.rpm
	chkconfig mongod on
	
	cp /etc/mongod.conf /etc/mongod.conf.bak
	wget -q -O /etc/mongod.conf $DL_REPO_ROOT/centos6/etc/mongod.conf
	wget -q -O /var/lib/mongo/auth_key $DL_REPO_ROOT/centos6/misc/mongo/auth_key
	chown mongod:mongod /var/lib/mongo/auth_key && chmod 600 /var/lib/mongo/auth_key
	
	/etc/init.d/mongod start
fi

echo
log 37 "Installation Completed"

exit 0
